# config.yaml
# Workflow: Snakemake-GATKv4.4-Snpeff-Workflow
# Version: 1.0
# Author: Dr. Ravi Prabhakar More (Email: ravipmore7@gmail.com)
# Date: 31-08-2023
samples:
  - NA24631

genome: "/YourPathToDir/hg38/gatk_bundle/Homo_sapiens_assembly38.fasta"
known_sites_dbsnp: "/YourPathToDir/hg38/gatk_bundle/dbsnp_146.hg38.vcf.gz"
known_sites_Mills_1000G: "/YourPathToDir/hg38/gatk_bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
known_sites_indels: "/YourPathToDir/hg38/gatk_bundle/Homo_sapiens_assembly38.known_indels.vcf.gz"
snpeff_config: "/YourPathToDir/snpEff/snpEff.config"
snpeff_jar: "/YourPathToDir/snpEff/snpEff.jar"
java_path: "/YourPathToDir/jdk-19.0.2/bin"
temp_dir: "/YourPathToDir/temp"